# vim:ft=kitty

## name: Kanagawa Black
## author: Code
## based-on: Kanagawa
## blurb: Opaque black Kitty palette using Kanagawa.nvim-inspired colors.

#: The basic colors

foreground                      #dcd7ba
background                      #000000
selection_foreground            #000000
selection_background            #e6c384

#: Cursor colors

cursor                          #c8c093
cursor_text_color               #000000

#: URL underline color when hovering with mouse

url_color                       #7fb4ca

#: Window and tab colors

active_border_color             #7e9cd8
inactive_border_color           #16161d
bell_border_color               #e46876
tab_bar_background              #000000
active_tab_foreground           #000000
active_tab_background           #c8c093
inactive_tab_foreground         #727169
inactive_tab_background         #0d0d12

#: The basic 16 colors

#: black
color0  #09090d
color8  #727169

#: red
color1  #c34043
color9  #e46876

#: green
color2  #76946a
color10 #98bb6c

#: yellow
color3  #c0a36e
color11 #e6c384

#: blue
color4  #7e9cd8
color12 #7fb4ca

#: magenta
color5  #957fb8
color13 #b8a3d4

#: cyan
color6  #6a9589
color14 #7aa89f

#: white
color7  #c8c093
color15 #dcd7ba

color16 #ffa066
color17 #ff5d62
