# vim:ft=kitty

## name: Kanagawa Glass
## author: Code
## based-on: Kanagawa
## blurb: Warm low-glare palette tuned for transparent Kitty windows and Operator Mono.

#: The basic colors

foreground                      #f4efda
background                      #111118
selection_foreground            #111118
selection_background            #e6c384

#: Cursor colors

cursor                          #f6d58d
cursor_text_color               #111118

#: URL underline color when hovering with mouse

url_color                       #7fb4ca

#: Window and tab colors

active_border_color             #8ba4f9
inactive_border_color           #2b2b38
bell_border_color               #e46876
tab_bar_background              #0d0d13
active_tab_foreground           #111118
active_tab_background           #d8b56e
inactive_tab_foreground         #969388
inactive_tab_background         #17171f

#: The basic 16 colors

#: black
color0  #0b0b11
color8  #8a887f

#: red
color1  #c34043
color9  #e46876

#: green
color2  #76946a
color10 #98bb6c

#: yellow
color3  #c0a36e
color11 #e6c384

#: blue
color4  #7e9cd8
color12 #7fb4ca

#: magenta
color5  #957fb8
color13 #b8a3d4

#: cyan
color6  #6a9589
color14 #7aa89f

#: white
color7  #d9d1b7
color15 #fff7dd

color16 #ffa066
color17 #ff5d62
