# vim:ft=kitty

## name: Kanagawa Black
## source: local Kanagawa.nvim-inspired black palette

foreground               #dcd7ba
background               #000000
background_tint          0.0
selection_foreground     #000000
selection_background     #e6c384

cursor                   #c8c093
cursor_text_color        #000000

url_color                #7fb4ca

active_border_color      #7e9cd8
inactive_border_color    #16161d
bell_border_color        #e46876
tab_bar_background       #000000
active_tab_foreground    #000000
active_tab_background    #c8c093
inactive_tab_foreground  #727169
inactive_tab_background  #0d0d12

color0   #09090d
color8   #727169

color1   #c34043
color9   #e46876

color2   #76946a
color10  #98bb6c

color3   #c0a36e
color11  #e6c384

color4   #7e9cd8
color12  #7fb4ca

color5   #957fb8
color13  #b8a3d4

color6   #6a9589
color14  #7aa89f

color7   #c8c093
color15  #dcd7ba

color16  #ffa066
color17  #ff5d62
