# vim:ft=kitty

## name: Rose Pine Dawn Minimal
## source: adapted from k0nserv dotfiles and rose-pine/kitty

foreground               #494467
background               #faf4ed
background_tint          0.58
selection_foreground     #faf4ed
selection_background     #907aa9

cursor                   #ea9d34
cursor_text_color        #faf4ed

url_color                #907aa9

active_border_color      #56949f
inactive_border_color    #dfdad9
tab_bar_background       #f4ede7
active_tab_foreground    #faf4ed
active_tab_background    #907aa9
inactive_tab_foreground  #7f7a96
inactive_tab_background  #f2e9e1

color0   #f2e9e1
color8   #7f7a96

color1   #b4637a
color9   #c06a84

color2   #286983
color10  #2f7d9b

color3   #ea9d34
color11  #f2b24e

color4   #56949f
color12  #6caab5

color5   #907aa9
color13  #a28dbc

color6   #d7827e
color14  #e09490

color7   #494467
color15  #2f2b45
