# vim:ft=kitty

## name: Rose Pine Minimal
## source: adapted from k0nserv dotfiles and rose-pine/kitty

foreground               #e8e3ff
background               #191724
background_tint          0.48
selection_foreground     #191724
selection_background     #f6c177

cursor                   #f6c177
cursor_text_color        #191724

url_color                #c4a7e7

active_border_color      #9ccfd8
inactive_border_color    #403d52
tab_bar_background       #13111d
active_tab_foreground    #191724
active_tab_background    #f6c177
inactive_tab_foreground  #908caa
inactive_tab_background  #26233a

color0   #26233a
color8   #7c8192

color1   #eb6f92
color9   #ff8fb1

color2   #7fbc8f
color10  #9ad3a8

color3   #f6c177
color11  #ffd38a

color4   #9ccfd8
color12  #b8e4ec

color5   #c4a7e7
color13  #d8bdf8

color6   #ebbcba
color14  #f4d2d0

color7   #e0def4
color15  #f7f4ff
