#!/usr/bin/env bash
# sync-hooks.sh - Synchronize hook enforcement across all AI tools
#
# Reads from: ~/.config/agentic/hooks/skill-map.json (single source of truth)
# Updates:
#   1. Factory Droid CLI shell wrappers (creates missing ones)
#   2. OpenCode oh-my-opencode.json prompt_append (regenerates skill tables)
#
# Run this after changing skill-map.json to propagate to all tools.

set -euo pipefail

CONFIG="$HOME/.config/agentic/hooks/skill-map.json"
FACTORY_HOOKS="$HOME/.factory/hooks"
FACTORY_SETTINGS="$HOME/.factory/settings.json"
OH_MY_OPENCODE="$HOME/.config/agentic/opencode/oh-my-opencode.json"

if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: $CONFIG not found"
  exit 1
fi

echo "=== Sync Hooks from skill-map.json ==="
echo ""

# ============================================================================
# 1. Ensure Factory shell wrappers exist for all Claude Code hooks
# ============================================================================
echo "--- Factory Droid CLI ---"

CLAUDE_HOOKS="$HOME/.claude/hooks"
for hook in "$CLAUDE_HOOKS"/require-*.py; do
  [[ -f "$hook" ]] || continue
  base=$(basename "$hook" .py)
  wrapper="$FACTORY_HOOKS/${base}.sh"

  if [[ ! -f "$wrapper" ]]; then
    echo "  Creating: $wrapper"
    cat > "$wrapper" << WRAPPER_EOF
#!/usr/bin/env bash
# PreToolUse hook: ${base} (auto-generated by sync-hooks.sh)
# Delegates to ~/.claude/hooks/${base}.py

set -euo pipefail
input=\$(cat)
if [[ -z "\$input" ]]; then exit 0; fi
echo "\$input" | python3 ~/.claude/hooks/${base}.py
exit \$?
WRAPPER_EOF
    chmod +x "$wrapper"
  else
    echo "  Exists: $wrapper"
  fi
done

# Check if Factory settings.json has all hooks registered
echo ""
echo "  Checking Factory settings.json registration..."
for hook in "$CLAUDE_HOOKS"/require-*.py; do
  [[ -f "$hook" ]] || continue
  base=$(basename "$hook" .py)
  if grep -q "$base" "$FACTORY_SETTINGS" 2>/dev/null; then
    echo "    Registered: $base"
  else
    echo "    MISSING: $base -- add to $FACTORY_SETTINGS PreToolUse hooks"
  fi
done

# ============================================================================
# 2. Generate the skill table for OpenCode prompt_append
# ============================================================================
echo ""
echo "--- OpenCode Prompt Generation ---"

# Build the markdown table from skill-map.json
SKILL_TABLE=$(python3 << 'PYEOF'
import json, sys
from pathlib import Path

config_path = Path.home() / ".config" / "agentic" / "hooks" / "skill-map.json"
with open(config_path) as f:
    config = json.load(f)

lines = []
lines.append("\\n## Mandatory Language Skill Rule\\n")
lines.append("Before editing ANY code file, you MUST invoke the relevant language skill:\\n")
lines.append("| Extension | Skill to Invoke |")
lines.append("|-----------|----------------|")

# Extensions
for ext, cfg in sorted(config.get("extensions", {}).items()):
    skills = ", ".join(cfg["skills"])
    lines.append(f"| {ext} | {skills} |")

# TypeScript
ts_exts = "/".join(config.get("typescript_extensions", []))
ts_skills = ", ".join(config.get("typescript_config", {}).get("skills", []))
if ts_exts:
    lines.append(f"| {ts_exts} | {ts_skills} |")

sec = config.get("security_skill", "")
if sec:
    lines.append(f"\\nAlso invoke `{sec}` for security-sensitive code.")

lines.append("\\nBypass with: 'skip skill' or 'no skill needed' from the user.\\n")

print("\\n".join(lines))
PYEOF
)

echo "  Generated skill table:"
echo "$SKILL_TABLE" | head -5
echo "  ..."

# Show current state
if [[ -f "$OH_MY_OPENCODE" ]]; then
  AGENTS_WITH_RULE=$(python3 -c "
import json
with open('$OH_MY_OPENCODE') as f:
    data = json.load(f)
count = 0
for name, cfg in data.get('agents', {}).items():
    if 'Language Skill Rule' in cfg.get('prompt_append', ''):
        count += 1
        print(f'    {name}')
print(f'  Total: {count} agents have the skill rule')
")
  echo ""
  echo "  Agents with skill rule in oh-my-opencode.json:"
  echo "$AGENTS_WITH_RULE"
  echo ""
  echo "  To update prompts, edit oh-my-opencode.json and replace the"
  echo "  '## Mandatory Language Skill Rule' section with the table above."
fi

echo ""
echo "=== Sync Complete ==="
echo ""
echo "Changes to skill-map.json are automatically picked up by:"
echo "  - Claude Code (require-skill.py reads JSON at runtime)"
echo "  - Factory Droid (delegates to require-skill.py)"
echo "  - OpenCode JS plugin (reads JSON at startup)"
echo ""
echo "OpenCode prompt_append must be updated manually (shown above)."
