[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "OperatorMonoSSm Nerd Font"
style = "Book"

[font.italic]
family = "OperatorMonoSSm Nerd Font"
style = "Book Italic"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u0003"

# Key bindings for tmux window navigation
[[keyboard.bindings]]
key = "T"
mods = "Alt"

[keyboard.bindings.command]
args = ["new-window", "-c", "~"]
program = "tmux"

[[keyboard.bindings]]
key = "W"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["kill-window"]
program = "tmux"


[[keyboard.bindings]]
chars = "\u0002x" # Send Ctrl-b + x
key = "W"
mods = "Alt"

[[keyboard.bindings]]
key = "{"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["select-window", "-t", "-1"]
program = "tmux"

[[keyboard.bindings]]
key = "}"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["select-window", "-t", "+1"]
program = "tmux"

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt|Super"

[keyboard.bindings.command]
args = ["swap-window", "-t", "-1", ";", "select-window", "-t", "-1"]
program = "tmux"

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt|Super"

[keyboard.bindings.command]
args = ["swap-window", "-t", "+1", ";", "select-window", "-t", "+1"]
program = "tmux"

[[keyboard.bindings]]
key = "L"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["split-window", "-h"]
program = "tmux"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["split-window", "-v"]
program = "tmux"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Enter"
mods = "Alt"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[window.padding]
x = 3
y = 1

#[env]
#TERM = "xterm-256color-italic"
